swagger: '2.0'
info:
  title: Sushify Gateway
  description: Sushify
  version: 1.0.0
host: hoge.app
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://hoge.app
  protocol: h2
paths:
  /generate/sushi:
    post:
      summary: Generate
      operationId: generate-sushi
      responses:
        '200':
          description: A successful response
          schema:
            type: string
securityDefinitions:
  # This section configures basic authentication with an API key.
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"